name: EEG-Pype

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11

  # Core packages
  - pip
  - mne=1.9.0
  - networkx=3.4.2
  - numpy=1.26.4
  - pandas=2.2.2
  - psutil=5.9.8
  - antropy=0.1.6
  - scipy=1.13.1
  - pyqt=5.15

  # Other important dependencies
  - matplotlib=3.9.0 # If your scripts generate plots
  - scikit-learn=1.5.0 # If used (not in direct imports, but common in analysis)
  - h5py=3.11.0 # For saving/loading data in HDF5 format (e.g., MNE)
  - openpyxl=3.1.2 # For pandas to read/write Excel .xlsx files
  - joblib=1.4.2 # Often used by scikit-learn and MNE for parallel processing
  - tqdm=4.66.4 # For progress bars
  - requests=2.32.2 # If you fetch data from web
  - jinja2=3.1.4 # Often a dependency for other packages like nbconvert or sphinx

  - pip:
    - PySimpleGUI==5.0.4 --extra-index-url https://PySimpleGUI.net/install
