name: EEG-Pype

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11

  # Core packages
  - pip
  - mne=1.9.0
  - networkx=3.4.2
  - numpy=1.26.4
  - pandas=2.2.2
  - psutil=5.9.8
  - antropy=0.1.6
  - scipy=1.13.1
  - pyqt=5.15

  # Other dependencies
  - matplotlib=3.9.0
  - scikit-learn=1.5.0
  - h5py=3.11.0
  - openpyxl=3.1.2
  - joblib=1.4.2
  - tqdm=4.66.4

  - pip:
    - PySimpleGUI==5.0.4 --extra-index-url https://PySimpleGUI.net/install
